version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - FLASK_FRONTEND_URL=${FRONTEND_URL}:${FRONTEND_PORT}
      - NEWS_API_KEY=${NEWS_API_KEY}=
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8080  
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}:${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
volumes:
  postgres_data: