version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}:${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - FLASK_FRONTEND_URL=${FRONTEND_URL}:${FRONTEND_PORT}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8080
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres-production
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network

networks:
  app-network:
